# sudo docker-compose config - ensure env vars load properly

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    depends_on:
      - postgres
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - GITEA____APP_NAME=${GITEA_WEBAPP_TITLE}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=${POSTGRES_DB_NAME}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
      - GITEA__server__PROTOCOL=https
      - GITEA__server__DOMAIN=${GITEA_WEBAPP_DOMAIN}
      - GITEA__server__ROOT_URL=${GITEA_WEBAPP_ROOT_URL}
      - GITEA__server__CERT_FILE=${GITEA_WEBAPP_CERT_FILE}
      - GITEA__server__KEY_FILE=${GITEA_WEBAPP_KEY_FILE}
    ports:
      - "${GITEA_WEBAPP_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - ${GITEA_DATA_PATH}:/data
      - ./certs:/etc/ssl:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DB_PATH}:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "${ADMINER_PORT}:8080"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    environment:
      - NGINX_SSL_CERT=${SSL_CERTIFICATE_NAME}
      - NGINX_SSL_CERT_KEY=${SSL_CERTIFICATE_KEY_NAME}
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
      - NGINX_ROOT_DIR=${NGINX_ROOT_DIR_CONTAINER}
      - NGINX_GITEA_PROXY_CERT=${GITEA_WEBAPP_CERT_FILE}
      - NGINX_GITEA_PROXY_CERT_KEY=${GITEA_WEBAPP_KEY_FILE}
    ports:
      - "${NGINX_HTTP_LISTEN_PORT}:80"
      - "${NGINX_HTTPS_LISTEN_PORT}:443"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/templates:/etc/nginx/templates:ro
      - ${NGINX_ROOT_DIR_HOST}:${NGINX_ROOT_DIR_CONTAINER}:ro
      - ${NGINX_LOG_DIR_HOST}:${NGINX_LOG_DIR_CONTAINER}
      - ./certs:/etc/ssl:ro
