# sudo docker-compose config - ensure env vars load properly

version: '3.1'

services:
  gitea:
    image: gitea/gitea
    container_name: gitea
    depends_on:
      - postgres
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - GITEA____APP_NAME=${GITEA_WEBAPP_TITLE}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=${POSTGRES_DB_NAME}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
      - GITEA__server__DOMAIN=${GITEA_WEBAPP_DOMAIN}
      - GITEA__server__ROOT_URL=${GITEA_WEBAPP_ROOT_URL}
    ports:
      - "${GITEA_WEBAPP_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - ${GITEA_DATA_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ${POSTGRES_DB_PATH}:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '${ADMINER_PORT}:8080'

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./config/nginx/${NGINX_CONF_FILE}:/etc/nginx/conf.d/${NGINX_CONF_FILE}:ro
      - ./html:/usr/share/nginx/html:ro
      - ./logs/nginx:/var/log/nginx